services:

  ws-server-go:
    container_name: ws-server-go
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ws-server-go
    ports:
      - "8080:8080"

  ws-server-rs:
    container_name: ws-server-rs
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ws-server-rs
    ports:
      - "8081:8081"

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: prometheus
    ports:
      - "9090:9090"

#  grafana-alloy:
#    container_name: grafana-alloy
#    restart: unless-stopped
#    build:
#      dockerfile: Dockerfile
#      context: grafana-alloy
#    ports:
#      - "12345:12345"
#    links:
#      - ws-server-go
#      - ws-server-rs
#      - prometheus

  fluent-bit:
    container_name: fluent-bit
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: fluent-bit
    ports:
      - "2021:2021"
    links:
      - ws-server-go
      - ws-server-rs
      - prometheus
